# Site settings
title: 'Matcha' # Your Title
tagline: 'A Healthy Green Drink' # A brief tagline for your site
sidebar_image: /images/cover.jpg
resource_image: /images/color.jpg
date: 2015-10-07 12:00:00

# Build settings
markdown: redcarpet
highlighter: pygments
url: http://localhost:4000
#baseurl: /Matcha # the subpath of your site, e.g. /blog/

# Permalinks
permalink: /:title
relative_permalinks: true
